###Register

POST http://localhost:8080/api/v1/users
Content-Type: application/json
Accept: application/json

{
  "name": "Ini nama",
  "email": "iniemail@test.com",
  "occupation": "Anak Band",
  "password": "ini password"
}

###GetCampaign
GET http://localhost:8080/api/v1/campaigns?user_id=100
Accept: application/json

###StaticFiles
GET http://localhost:8080/images/1-cls45amg.jpg
Accept: image/jpeg